---
node_red_enabled: false
node_red_available_externally: false

# directories
node_red_data_directory: "{{ homations_docker_data }}/nodered/"

# network
node_red_port: "1880"
node_red_hostname: "nodered"
node_red_ip_allowlist: "0.0.0.0/0"

# docker
node_red_container_name: "nodered"
node_red_image_name: "nodered/node-red"
node_red_image_version: "4.0.5"
node_red_restart_policy: "unless-stopped"
node_red_volume_name: "{{ node_red_container_name }}_data"

# specs
node_red_memory: 1g
