---
- name: Start Nextcloud
  when: nextcloud_enabled is true
  block:
    - name: Create Nextcloud Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ nextcloud_data_directory }}"
        - "{{ nextcloud_db_data_directory }}"

    - name: Create Redis Directories
      when: nextcloud_cache_enabled is true
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ nextcloud_cache_directory }}"

    - name: Create Docker Network
      docker_network:
        name: "{{ nextcloud_intra_network_name }}"

    - name: Redis Docker Container
      when: nextcloud_cache_enabled is true
      community.docker.docker_container:
        name: "{{ nextcloud_cache_container_name }}"
        image: "{{ nextcloud_cache_image_name }}:{{ nextcloud_cache_image_version }}"
        image_name_mismatch: "recreate"
        pull: true
        restart_policy: "{{ nextcloud_cache_restart_policy }}"
        # memory: "{{ nextcloud_cache_memory }}"
        volumes:
          - "{{ nextcloud_cache_directory }}:/data"
        networks:
          - name: "{{ nextcloud_intra_network_name }}"
        command: "redis-server --requirepass {{ nextcloud_cache_password }}"
        
    - name: Postgres Docker Container
      community.docker.docker_container:
        name: "{{ nextcloud_db_container_name }}"
        image: "{{ nextcloud_db_image_name }}:{{ nextcloud_db_image_version }}"
        image_name_mismatch: "recreate"
        pull: true
        restart_policy: "{{ nextcloud_db_restart_policy }}"
        # memory: "{{ nextcloud_db_memory }}"
        environment:
          - "POSTGRES_DB={{ nextcloud_db_name }}"
          - "POSTGRES_USER={{ nextcloud_db_user }}"
          - "POSTGRES_PASSWORD={{ nextcloud_db_password }}"
        volumes:
          - "{{ nextcloud_db_data_directory }}:/var/lib/postgresql/data"
        networks:
          - name: "{{ nextcloud_intra_network_name }}"

    - name: Nextcloud Docker Container
      vars:
          homations_proxy_docker_network:
            - name: "{{ homations_traefik_network }}"
          homations_internal_docker_network:
            - name: "{{ homations_internal_network }}"
          nextcloud_intra_network:
            - name: "{{ nextcloud_intra_network_name }}"
          nextcloud_docker_network: "{{ nextcloud_intra_network + homations_internal_docker_network + homations_proxy_docker_network if nextcloud_available_externally else nextcloud_intra_network + homations_internal_docker_network }}"
          optional_environment:
            - "REDIS_HOST={{ nextcloud_cache_container_name }}"
            - "REDIS_HOST_PASSWORD={{ nextcloud_cache_password }}"
          required_environment:
            - "POSTGRES_HOST={{ nextcloud_db_container_name }}"
            - "POSTGRES_DB={{ nextcloud_db_name }}"
            - "POSTGRES_USER={{ nextcloud_db_user }}"
            - "POSTGRES_PASSWORD={{ nextcloud_db_password }}"
            - "NEXTCLOUD_ADMIN_USER={{ nextcloud_admin_user }}"
            - "NEXTCLOUD_ADMIN_PASSWORD={{ nextcloud_admin_password }}"
          nextcloud_environment: "{{ optional_environment + required_environment if nextcloud_cache_enabled else required_environment }}"
      community.docker.docker_container:
        name: "{{ nextcloud_container_name }}"
        image: "{{ nextcloud_image_name }}:{{ nextcloud_image_version }}"
        image_name_mismatch: "recreate"
        pull: true
        restart_policy: "{{ nextcloud_restart_policy }}"
        # memory: "{{ nextcloud_db_memory }}"
        environment: "{{ nextcloud_environment }}"
        volumes:
          - "{{ nextcloud_data_directory }}:/var/www/html"
        networks: "{{ nextcloud_docker_network }}"
        labels:
          traefik.enable: "{{ nextcloud_available_externally | string }}"
          traefik.http.routers.nextcloud.rule: "Host(`{{ nextcloud_hostname }}.{{ homations_domain }}`)"
          traefik.http.routers.nextcloud.tls.certresolver: "dnsresolver"
          traefik.http.routers.nextcloud.tls.domains[0].main: "{{ homations_domain }}"
          traefik.http.routers.nextcloud.tls.domains[0].sans: "*.{{ homations_domain }}"
          traefik.http.services.nextcloud.loadbalancer.server.port: "{{ nextcloud_port }}"
          traefik.http.middlewares.nextcloud-ipwhitelist.ipwhitelist.sourcerange: "{{ nextcloud_ip_whitelist }}"
          traefik.http.routers.nextcloud.middlewares: "nextcloud-ipwhitelist@docker"

- name: Stop Nextcloud Stack
  when: nextcloud_enabled is false
  block:
    - name: Stop Redis
      community.docker.docker_container:
        name: "{{ nextcloud_cache_container_name }}"
        state: absent

    - name: Stop Postgres
      community.docker.docker_container:
        name: "{{ nextcloud_db_container_name }}"
        state: absent

    - name: Stop Nextcloud
      community.docker.docker_container:
        name: "{{ nextcloud_container_name }}"
        state: absent

    - name: Delete Docker Network
      docker_network:
        name: "{{ nextcloud_intra_network_name }}"
        state: absent
        force: yes
