---
- name: Start MKTXP-Exporter
  when: observability_mktxp_exporter_enabled is true
  block:
    - name: Create MKTXP Directory
      ansible.builtin.file:
        path: "{{ observability_mktxp_exporter_config_directory }}"
        state: directory

    - name: Template mktxp.conf
      ansible.builtin.template:
        src: mktxp.conf.j2
        dest: "{{ observability_mktxp_exporter_config_directory }}/mktxp.conf"
      register: mktxp_conf_template_config

    - name: MKTXP-Exporter Docker Container
      community.docker.docker_container:
        name: "{{ observability_mktxp_exporter_container_name }}"
        image: "{{ observability_mktxp_exporter_image_name }}:{{ observability_mktxp_exporter_image_version }}"
        image_name_mismatch: "recreate"
        pull: true
        # user: shei
        volumes:
          - "{{ observability_mktxp_exporter_config_directory }}:/root/mktxp/mktxp.conf"
        networks:
          - name: "{{ homations_internal_network }}"
        restart_policy: "{{ observability_mktxp_exporter_restart_policy }}"
        restart: "{{ mktxp_conf_template_config.changed }}"
        # memory: "{{ observability_mktxp_exporter_memory }}"

- name: Stop MKTXP-Exporter
  when: observability_mktxp_exporter_enabled is false
  block:
    - name: Stop mktxp-Exporter
      community.docker.docker_container:
        name: "{{ observability_mktxp_exporter_container_name }}"
        state: absent
