---
observability_mktxp_exporter_enabled: false

# directories
observability_mktxp_exporter_config_directory: "{{ homations_docker_config }}/mktxp"

# docker
observability_mktxp_exporter_container_name: "mktxp-exporter"
observability_mktxp_exporter_image_name: "ghcr.io/akpw/mktxp"
observability_mktxp_exporter_image_version: "1.2.9"
observability_mktxp_exporter_restart_policy: "unless-stopped"

# specs
observability_mktxp_exporter_memory: 1g
#
# mikrotik hardware
# mikrotik:
#   - name: CRS
#     ip: <ip>
#   - name: cAP
#     ip: <ip>
