---
- name: Start Loki
  when: observability_loki_enabled is true
  vars:
    observability_loki_config_file_name: "loki.yml"
    observability_loki_host_config_file_path: "{{ observability_loki_config_directory }}/{{ observability_loki_config_file_name }}"
  block:
    - name: Create Loki Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ observability_loki_data_directory }}"
        - "{{ observability_loki_config_directory }}"

    - name: Create the Loki Docker Volume
      when: homations_docker_volume_enabled is true
      community.docker.docker_volume:
        name: "{{ observability_loki_volume_name }}"
        driver: local
        driver_options:
          type: none
          device: "{{ observability_loki_data_directory }}"
          o: bind

    - name: Template loki.yml
      ansible.builtin.template:
        src: loki.yml.j2
        dest: "{{ observability_loki_host_config_file_path }}"
      register: observability_loki_template_config

    - name: Loki Docker Container
      vars:
        observability_loki_container_config_file_path: "/etc/loki/{{ observability_loki_config_file_name }}"
        observability_loki_volume_spec: "{{ observability_loki_volume_name if (homations_docker_volume_enabled) else observability_loki_data_directory }}"
      community.docker.docker_container:
        name: "{{ observability_loki_container_name }}"
        image: "{{ observability_loki_image_name }}:{{ observability_loki_image_version }}"
        image_name_mismatch: "recreate"
        user: "1000:1000"
        pull: true
        volumes:
          - "{{ observability_loki_volume_spec }}:/loki:rw"
          - "{{ observability_loki_host_config_file_path }}:{{ observability_loki_container_config_file_path }}"
          - "/etc/timezone:/etc/timezone:ro"
        networks:
          - name: "{{ homations_internal_network }}"
        restart_policy: "{{ observability_loki_restart_policy }}"
        # memory: "{{ observability_loki_memory }}"
        command:
          - "--config.file={{ observability_loki_container_config_file_path }}"

- name: Stop Loki
  when: observability_loki_enabled is false
  block:
    - name: Stop Loki
      community.docker.docker_container:
        name: "{{ observability_loki_container_name }}"
        state: absent

    - name: Remove the Loki Docker Volume
      when: homations_docker_volume_enabled
      community.docker.docker_volume:
        name: "{{ observability_loki_volume_name }}"
        state: absent
