---
- name: Start Node-RED
  when: node_red_enabled is true
  block:
    - name: Create Node-RED Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ node_red_data_directory }}"

    - name: Node-RED Docker Container
      community.docker.docker_container:
        name: "{{ node_red_container_name }}"
        image: "{{ node_red_image_name }}:{{ node_red_image_version }}"
        image_name_mismatch: "recreate"
        pull: true
        env: TZ={{ homations_timezone }}
        networks: "{{ node_red_docker_network }}"
        volumes:
          - "{{ node_red_data_directory }}:/data:rw"
        restart_policy: "{{ node_red_restart_policy }}"
        # memory: "{{ node_red_memory }}"
        labels:
          traefik.enable: "{{ node_red_available_externally | string }}"
          traefik.http.routers.nodered.rule: "Host(`{{ node_red_hostname }}.{{ homations_domain }}`)"
          traefik.http.routers.nodered.tls.certresolver: "dnsresolver"
          traefik.http.routers.nodered.tls.domains[0].main: "{{ homations_domain }}"
          traefik.http.routers.nodered.tls.domains[0].sans: "*.{{ homations_domain }}"
          traefik.http.services.nodered.loadbalancer.server.port: "1880"
          traefik.http.middlewares.nodered-ipallowlist.ipallowlist.sourcerange: "{{ node_red_ip_allowlist }}"
          traefik.http.routers.nodered.middlewares: "nodered-ipallowlist@docker"

- name: Stop Node-RED
  when: node_red_enabled is false
  block:
    - name: Stop Node-RED
      community.docker.docker_container:
        name: "{{ node_red_container_name }}"
        state: absent
